runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /microdemocracy
  static_files: microdemocracy.html
  upload: microdemocracy.html
- url: /process
  static_files: process.html
  upload: process.html
