runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index
  upload: index
  mime_type: text/html
- url: /([^./]*)
  static_files: \1
  upload: ([^./]*)
  mime_type: text/html
- url: /_resources
  static_dir: _resources

