runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: _public/index
  upload: _public/index
  mime_type: text/html
- url: /([^./]*)
  static_files: _public/\1
  upload: _public/([^./]*)
  mime_type: text/html
- url: /_resources
  static_dir: _public/_resources

